### ISSUE TITLE
How to generate device public key

### ISSUE THREAD

**Issue by rjjrbatarao** [ciniml/WireGuard-ESP32-Arduino#12]
Is there any way of getting the device public key? theres only peer public key available but I dont know where to get the device public key

**Comment by ciniml** [comment]
This library does not have any key generation feature, so you must generate a device private and public key pair somewhere else. 
e.g. Generating the device private and public keys on a PC with [this instruction](https://www.wireguard.com/quickstart/).

Then you can embed the generated private key to the sketch and register the generated public key to the WireGuard remote peer.

**Comment by rjjrbatarao** [comment]
Thank you I'll follow the instruction right away.

**Comment by rjjrbatarao** [comment]
I found an online tool t generate private nad public key https://www.wireguardconfig.com/  hope this helps.
