### ISSUE TITLE
Config connects on any other device, except on ESP32

### ISSUE THREAD

**Issue by KoenHaemels** [ciniml/WireGuard-ESP32-Arduino#24]
I'm looking for a couple of days now what is wrong with the setup.
Wireguard is running on my pfSense and i have created a peer for my ESP32.
The config works on any other device i'm trying, but if i use it on a ESP32 it doesn't connect.

I'm using the example-code, changed the keys and won't see a handshake in my pfSense.

**Comment by KoenHaemels** [comment]
There was combination of 2 profiles on my 2 computers.
Created a new one, everything is working now.

**Comment by distancerunner** [comment]
How did you solve this handshake problem? It looks like my problem here: #29
